;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-visual-line
        electric-newline-and-maybe-indent
        end-of-visual-line
        eval-print-last-sexp
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-insert
        evil-next-line
        evil-normal-state
        evil-paste-pop
        evil-scroll-page-down
        forward-sexp
        kill-region
        kill-visual-line
        magit-status
        markdown-outdent-or-delete
        org-delete-char
        org-metaright
        org-return-indent
        org-self-insert-command
        org-yank
        paredit-backward
        paredit-forward
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-newline
        paredit-open-round
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-kill-region
        sp-kill-word
        sp-splice-sexp
        yaml-electric-backspace
        yaml-electric-bar-and-angle
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        iedit-switch-to-mc-mode
        ))
