;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        evil-delete-backward-char-and-join
        evil-insert
        kill-region
        magit-status
        org-metaright
        org-self-insert-command
        paredit-backward
        paredit-forward
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-newline
        paredit-open-round
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        ))
