;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        end-of-visual-line
        eval-print-last-sexp
        evil-delete-backward-char-and-join
        evil-insert
        evil-normal-state
        kill-region
        magit-status
        org-metaright
        org-self-insert-command
        paredit-backward
        paredit-forward
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-newline
        paredit-open-round
        sp-backward-delete-char
        sp-forward-sexp
        sp-kill-region
        sp-splice-sexp
        yaml-electric-backspace
        yaml-electric-bar-and-angle
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        ))
